### ISSUE TITLE
websocket add proxy

### ISSUE THREAD

**Issue by viokuma** [sammchardy/python-binance#248]
hi, I can't find how to set proxy on websocket api, please add it , thank you

**Comment by kenneth** [comment]
please add proxy option

**Comment by Frogkiller** [comment]
Hi,

I found out that proxy is not passed to websocket factory, changing manually websockets.py to this:
 ```
def _start_socket(self, path, callback, prefix='ws/'):
        if path in self._conns:
            return False

        factory_url = self.STREAM_URL + prefix + path
        factory = BinanceClientFactory(factory_url)
        factory.protocol = BinanceClientProtocol
        factory.callback = callback
        factory.reconnect = True
        factory.proxy = {'host' : '<proxy ip here>', 'port': <proxy port here>}
        context_factory = ssl.ClientContextFactory()

        self._conns[path] = connectWS(factory, context_factory)
        return path
```
is solving this issue. But it's hard do fix in generic way, as to client, proxy is passed through requests_params, where proxy is defined as dict:

`{'proxies': { 'http' : 'ip:port', 'https' : 'ip:port'}}`

I guess easiest way would be to add additional params to BinanceSocketManager.__init__ to accept host + port for proxy and use it in _start_socket, but it's up to devs if this is valid from their pov.

**Comment by kuailink** [comment]
I fixed it in my fork [kuailink/python-binance](https://github.com/kuailink/python-binance/commit/845548a2063065cfec1966c4d16167e889cf721d), thanks to the solution given above.

**Comment by simin75simin** [comment]
so i checked out kuailink's fork and made sure i uninstalled the python-binance before that, but it seems that it still won't talk through the socket. i'm using wrapper functions in the binance sentiment bot https://github.com/CyberPunkMetalHead/Binance-News-Sentiment-Bot.
